version: '3.8'

services:
  maskedmatch-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maskedmatch_web
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
