import { useRef, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { PhaserWorld, type PhaserWorldHandle } from '../../game/PhaserWorld'
import { COMPANIES, JOB } from '../../data/demo/fixtures'
import { useDemo } from '../../data/demo/DemoContext'
import { MatchScore, MobileNav, NetworkBadge, PixelButton, QueueChip, ReadyCheckDialog } from '../components'

export function WorldScreen() {
  const { state } = useDemo()
  const navigate = useNavigate()
  const [selected, setSelected] = useState('cyber-orchard')
  const [phaserReady, setPhaserReady] = useState(false)
  const world = useRef<PhaserWorldHandle>(null)
  const company = COMPANIES.find((item) => item.id === selected) ?? COMPANIES[0]
  return (
    <div className="world-page world-page--hall">
      <a className="skip-link" href="/event/demo/navigator">ข้ามโลกและเปิดโหมดรายการ</a>
      <header className="world-hud"><div><Link to="/event/demo" className="world-logo">MM</Link><div><strong>NEON CAREER HALL</strong><span>MAIN EXHIBITION FLOOR · LIVE</span></div></div><div className="hall-online" aria-label="มีผู้เข้าร่วมจำลอง 16 คนออนไลน์"><span>16 ONLINE</span><i>R</i><i>C</i><i>G</i><i>+</i></div><div className="world-hud__status"><NetworkBadge /><span className="badge badge--cyan">◇ BLIND MODE</span><span className="alias-chip">Candidate #8F3A</span></div></header>
      <div className="world-layout">
        <aside className="world-rail"><div className="rail-kicker">EXPLORE HALL</div><label className="search"><span aria-hidden="true">⌕</span><span className="sr-only">ค้นหางานหรือบริษัท</span><input placeholder="ค้นหางานหรือบริษัท" /></label><nav><Link className="is-active" to="/event/demo/world"><span>▦</span>แผนผังฮอลล์</Link><Link to="/event/demo/navigator"><span>☷</span>Navigator / รายการ</Link><a href="#recommended"><span>✦</span>งานแนะนำ <b>3</b></a><a href="#district"><span>⌂</span>บูธทั้งหมด</a><a href="#support"><span>?</span>Support & Quiet lounge</a></nav><div className="minimap"><header><span>HALL MAP</span><button aria-label="ขยายแผนที่">+</button></header><div><i className="mini-booth one" /><i className="mini-booth two" /><i className="mini-booth three" /><i className="mini-booth four" /><b aria-label="ตำแหน่งของคุณ" /></div><small>● คุณอยู่ที่ Main Entrance</small></div><div className="rail-help"><span>?</span><div><b>คุยกับ NPC ได้</b><small>แตะตัวละครเพื่อดูบทสนทนา</small></div></div></aside>
        <section className="world-canvas" aria-label="ภาพ Neon Career Hall แบบโต้ตอบ มี Navigator เป็นทางเลือกที่ใช้งานได้เทียบเท่า"><PhaserWorld ref={world} reducedMotion={state.reducedMotion} onReady={() => setPhaserReady(true)} onSelectBooth={(id) => setSelected(id)} /><div className="world-instruction"><span>WASD / ARROWS</span> เดิน · <span>CLICK / TAP</span> เลือกจุดเดิน · <span>E</span> เปิดบูธ · แตะ NPC เพื่อคุย</div><div className="world-dpad" aria-label="ปุ่มควบคุมการเดิน"><button className="world-dpad__up" aria-label="เดินขึ้น" onClick={() => world.current?.nudge(0, -1)}>▲</button><button className="world-dpad__left" aria-label="เดินซ้าย" onClick={() => world.current?.nudge(-1, 0)}>◀</button><button className="world-dpad__center" aria-label="กลับกลางฮอลล์" onClick={() => world.current?.recenter()}>●</button><button className="world-dpad__right" aria-label="เดินขวา" onClick={() => world.current?.nudge(1, 0)}>▶</button><button className="world-dpad__down" aria-label="เดินลง" onClick={() => world.current?.nudge(0, 1)}>▼</button></div><div className="world-recenter"><button aria-label="ซูมเข้า" onClick={() => world.current?.zoomIn()}>+</button><button aria-label="ซูมออก" onClick={() => world.current?.zoomOut()}>−</button><button aria-label="กลับมาตำแหน่งของฉัน" onClick={() => world.current?.recenter()}>⌖</button></div><div className={`hall-live-pill${phaserReady ? ' is-ready' : ''}`} role="status"><i /> {phaserReady ? 'PHASER LIVE' : 'LOADING PHASER'} <span>16 NPCs</span></div></section>
        <aside className="context-panel" id="recommended"><div className="context-panel__top"><span className="badge badge--pink">✦ BOOTH NEARBY</span><button aria-label="ปิดรายละเอียด">×</button></div><div className="company-symbol" style={{ '--company': company.accent } as React.CSSProperties}><span>{company.id.split('-').map(word => word[0]).join('').slice(0, 2).toUpperCase()}</span></div><p className="company-label">{company.district}</p><h1>{selected === 'cyber-orchard' ? JOB.title : selected === 'cloud-lantern' ? 'Platform Engineer' : selected === 'riverbyte' ? 'Product Designer' : 'Frontend Developer'}</h1><p className="company-name">{company.name} <span title="บริษัทจำลองที่ยืนยันใน demo">✓</span></p><MatchScore compact /><div className="reason-box"><strong>ทำไมงานนี้ถึงแนะนำ</strong><ul>{JOB.reasons.map((reason) => <li key={reason}>✓ <span>{reason}</span></li>)}</ul></div><div className="job-meta"><span><small>รูปแบบ</small><b>Hybrid</b></span><span><small>สัมภาษณ์</small><b>12 นาที</b></span><span><small>คิวปัจจุบัน</small><b>{company.queue}</b></span></div><p className="masked-note">◇ Recruiter เห็นเฉพาะทักษะและหลักฐานของคุณ</p><PixelButton className="button--full" onClick={() => navigate('/event/demo/booths/cyber-orchard/jobs/backend-developer')}>เข้าไปที่บูธ →</PixelButton><button className="text-button button--full">นำทางมาที่บูธ</button></aside>
      </div>
      <div className="world-queue"><QueueChip /></div><MobileNav /><ReadyCheckDialog />
    </div>
  )
}

export function NavigatorScreen() {
  const navigate = useNavigate()
  return (
    <div className="navigator-page"><header className="navigator-header"><Link to="/event/demo/world" className="world-logo">MM</Link><div><span className="eyebrow">ACCESSIBLE LIST MODE</span><h1>Navigator</h1></div><Link className="button button--secondary" to="/event/demo/world">เปิดแผนที่</Link></header><main><label className="search search--large"><span aria-hidden="true">⌕</span><span className="sr-only">ค้นหาตำแหน่ง ทักษะ หรือบริษัท</span><input placeholder="ค้นหาตำแหน่ง ทักษะ หรือบริษัท" /></label><div className="navigator-columns"><section><div className="section-title"><div><span>งานที่แนะนำ</span><h2>ตรงกับหลักฐานของคุณ</h2></div><small>DEMO MATCH RULE</small></div><article className="job-card job-card--featured"><div className="job-card__score"><b>92</b><span>/100</span></div><div className="job-card__body"><span className="badge badge--cyan">BLIND MODE</span><h3>{JOB.title}</h3><p>{JOB.company.name}</p><div className="skill-row skill-row--active">{JOB.mustHave.map(skill => <span key={skill}>{skill}</span>)}</div><small>เพราะ: {JOB.reasons.join(' · ')}</small></div><div className="job-card__action"><b>รอ 8–12 นาที</b><PixelButton onClick={() => navigate('/event/demo/booths/cyber-orchard/jobs/backend-developer')}>ดูรายละเอียด</PixelButton></div></article>{COMPANIES.slice(1).map((company, index) => <article className="job-card" key={company.id}><div className="job-card__score"><b>{86 - index * 7}</b><span>/100</span></div><div className="job-card__body"><h3>{index === 0 ? 'Platform Engineer' : index === 1 ? 'Product Designer' : 'Frontend Developer'}</h3><p>{company.name}</p><small>{company.district} · {company.queue}</small></div><div className="job-card__action"><PixelButton variant="secondary">ดูรายละเอียด</PixelButton></div></article>)}</section><aside><div className="side-card"><h2>คิวปัจจุบัน</h2><QueueChip /><p>ยังไม่มีคิว? เปิด Backend Developer แล้วกดเข้าคิวได้จากหน้านี้โดยไม่ต้องใช้แผนที่</p></div><div className="side-card" id="support"><h2>Support & Accessibility</h2><ul className="plain-list"><li>ใช้โหมดข้อความช่วยสัมภาษณ์</li><li>ขอเวลาเพิ่มเติม</li><li>รายงานปัญหาความเป็นส่วนตัว</li></ul><PixelButton variant="secondary" className="button--full">ติดต่อ Support</PixelButton></div></aside></div></main><MobileNav /><ReadyCheckDialog /></div>
  )
}

export function JobScreen() {
  const { state, dispatch } = useDemo()
  const navigate = useNavigate()
  const queueActive = Boolean(state.queue.id)
  return (
    <div className="detail-page"><header className="detail-header"><Link to="/event/demo/world">← กลับ Career City</Link><div><span className="badge badge--cyan">◇ BLIND MODE ACTIVE</span><NetworkBadge /></div></header><main><div className="job-hero"><div className="company-symbol company-symbol--large"><span>CO</span></div><div><span className="eyebrow">CYBER ORCHARD CO. · VERIFIED DEMO</span><h1>{JOB.title}</h1><p>{JOB.mode} · Full-time</p></div><MatchScore /></div><nav className="tabs"><a href="#overview" className="is-active">ภาพรวม</a><a href="#skills">ทักษะ</a><a href="#queue">คิวสัมภาษณ์</a><a href="#privacy">ข้อมูลที่มองเห็น</a></nav><div className="detail-grid"><section><article className="content-card" id="overview"><h2>สร้างระบบที่รับมือกับโลกจริง</h2><p>ดูแล backend services สำหรับแพลตฟอร์ม IoT จำลอง ออกแบบ API และ queue ที่คงทน พร้อมทำงานร่วมกับทีม product ขนาดเล็ก</p><div className="detail-facts"><span><small>รูปแบบงาน</small><b>Hybrid</b></span><span><small>ประเภท</small><b>Full-time</b></span><span><small>ช่วงเงินเดือน</small><b>45K–70K THB <em>DEMO</em></b></span></div></article><article className="content-card" id="skills"><h2>ทักษะที่มองหา</h2><h3>Must-have</h3><div className="requirements">{JOB.mustHave.map((skill) => <span key={skill}>✓ {skill}</span>)}</div><h3>Nice-to-have</h3><div className="requirements requirements--muted">{JOB.niceToHave.map((skill) => <span key={skill}>+ {skill}</span>)}</div></article><article className="content-card" id="privacy"><h2>Recruiter เห็นอะไรบ้าง?</h2><div className="visibility-table"><div><span>ทักษะ & หลักฐาน</span><b className="visible">✓ มองเห็น</b></div><div><span>ชื่อ / รูป / อายุ</span><b>— ซ่อนอยู่</b></div><div><span>อีเมล / โทรศัพท์</span><b>— ซ่อนอยู่</b></div><div><span>สถาบัน / นายจ้างเดิม</span><b>— ซ่อนอยู่</b></div></div></article></section><aside><div className="join-card" id="queue"><div className="queue-visual"><span>⌛</span><b>8–12</b><small>นาทีโดยประมาณ</small></div><h2>คิวกำลังเปิด</h2><p>มีผู้สมัคร 3 คนก่อนคุณ · สัมภาษณ์ประมาณ 12 นาที</p><ul><li>✓ เดินดูบูธอื่นระหว่างรอได้</li><li>✓ Refresh แล้วคิวยังอยู่</li><li>✓ ไม่เปิดกล้องโดยอัตโนมัติ</li></ul>{queueActive ? <><div className="success-message">✓ อยู่ในคิวแล้ว · ลำดับ #{state.queue.position}</div><PixelButton className="button--full" variant="secondary" onClick={() => navigate('/event/demo/world')}>กลับไปสำรวจเมือง</PixelButton></> : <PixelButton className="button--full" onClick={() => dispatch({ type: 'JOIN_QUEUE' })}>เข้าคิวสัมภาษณ์</PixelButton>}<small className="join-card__fine">ตำแหน่งและเวลารอเป็นค่าประมาณจาก demo</small></div></aside></div></main><div className="detail-queue"><QueueChip /></div><ReadyCheckDialog /></div>
  )
}
