import { ArrowRight, BriefcaseBusiness, Check, CheckCircle2, ClipboardCheck, FileText, RotateCcw, Search, ShieldCheck, Sparkles, Upload, Users } from "lucide-react";
import { type ChangeEvent, useMemo, useRef, useState } from "react";
import { analyzeResume, generateAssessment, type AssessmentQuestion } from "../services/resume-api";

type Job = { id: string; title: string; category: string; department: string; location: string; type: string; salary: string; summary: string; skills: string[]; questions: string[] };

const jobs: Job[] = [
  { id: "frontend", title: "Frontend Developer", category: "Tech", department: "Product Engineering", location: "Bangkok · Hybrid", type: "Full-time", salary: "฿55K–85K", summary: "พัฒนาเว็บแอปที่เร็ว เข้าถึงได้ และดูแล state/API อย่างเป็นระบบ", skills: ["React", "TypeScript", "REST API", "Testing"], questions: ["อธิบายวิธีลด unnecessary re-render ใน React", "ออกแบบ error handling เมื่อ API ล่มอย่างไร", "ยกตัวอย่าง test ที่ช่วยป้องกัน regression"] },
  { id: "data", title: "Data Analyst", category: "Tech", department: "Data & Insights", location: "Bangkok · Hybrid", type: "Full-time", salary: "฿45K–70K", summary: "เปลี่ยนข้อมูลธุรกิจเป็น insight และ dashboard ที่ใช้ตัดสินใจได้", skills: ["SQL", "Python", "Data Visualization", "Statistics"], questions: ["เขียนแนวคิด SQL หา monthly retention", "จะตรวจ data quality ก่อนทำ dashboard อย่างไร", "อธิบายความต่าง correlation และ causation"] },
  { id: "marketing", title: "Digital Marketing Specialist", category: "Business", department: "Marketing", location: "Bangkok · On-site", type: "Full-time", salary: "฿38K–58K", summary: "วางแคมเปญ วัด conversion และปรับงบจากข้อมูลจริง", skills: ["Campaign Strategy", "Google Analytics", "Content", "Performance Marketing"], questions: ["ออกแบบ funnel สำหรับสินค้าใหม่", "เลือก metric เพื่อวัด campaign อย่างไร", "ทำอย่างไรเมื่อ CAC สูงขึ้นต่อเนื่อง"] },
  { id: "sales", title: "B2B Sales Executive", category: "Business", department: "Sales", location: "Bangkok · Hybrid", type: "Full-time", salary: "฿35K–60K + commission", summary: "ดูแล pipeline ลูกค้าองค์กรตั้งแต่ discovery ถึงปิดการขาย", skills: ["B2B Sales", "Negotiation", "CRM", "Account Planning"], questions: ["เล่าวิธี qualify ลูกค้าองค์กร", "รับมือ objection เรื่องราคาอย่างไร", "จัดลำดับดีลใน pipeline จากอะไร"] },
  { id: "hr", title: "People Operations Officer", category: "People", department: "Human Resources", location: "Bangkok · On-site", type: "Full-time", salary: "฿32K–48K", summary: "ดูแล employee experience และกระบวนการ HR ให้แม่นยำ", skills: ["HR Operations", "Labour Law", "Onboarding", "Communication"], questions: ["ออกแบบ onboarding 30 วันอย่างไร", "จัดการข้อมูลพนักงานที่ละเอียดอ่อนอย่างไร", "ยกตัวอย่างการแก้ employee issue"] },
  { id: "finance", title: "Financial Planning Analyst", category: "Operations", department: "Finance", location: "Bangkok · Hybrid", type: "Full-time", salary: "฿48K–72K", summary: "ทำ budget, forecast และวิเคราะห์ผลต่างเพื่อสนับสนุนผู้บริหาร", skills: ["Financial Modeling", "Excel", "Forecasting", "Variance Analysis"], questions: ["สร้าง rolling forecast จากสมมติฐานใด", "อธิบาย favorable variance ที่อาจเป็นสัญญาณลบ", "ตรวจความถูกต้องของ financial model อย่างไร"] },
  { id: "ops", title: "Customer Operations Lead", category: "Operations", department: "Customer Experience", location: "Remote · Thailand", type: "Full-time", salary: "฿42K–65K", summary: "ยกระดับคุณภาพบริการด้วย SLA, coaching และ process improvement", skills: ["Customer Service", "SLA Management", "Process Improvement", "Team Coaching"], questions: ["จัดการ backlog ที่เกิน SLA อย่างไร", "วัดคุณภาพทีมบริการด้วย metric ใด", "เล่าการปรับ process ที่ลดปัญหาซ้ำ"] },
];

const sampleClaims = "มีประสบการณ์ React และ TypeScript 3 ปี เชื่อมต่อ REST API และเขียน Testing ด้วย Vitest เคยปรับ performance dashboard จนเวลาโหลดลดลง 35% และดูแล accessibility ตาม WCAG";

function scoreFor(job: Job, claims: string) {
  const normalized = claims.toLowerCase();
  const matched = job.skills.filter((skill) => normalized.includes(skill.toLowerCase()));
  const coverage = Math.round((matched.length / job.skills.length) * 100);
  const evidence = /ปี|%|โปรเจกต์|project|เคย|ผลลัพธ์|ลด|เพิ่ม/.test(normalized) ? 82 : 48;
  return { matched, missing: job.skills.filter((skill) => !matched.includes(skill)), score: Math.round(coverage * 0.65 + evidence * 0.35), evidence };
}

export function RecruiterDemoPage() {
  const [selectedJobId, setSelectedJobId] = useState(jobs[0]!.id);
  const [query, setQuery] = useState("");
  const [fileName, setFileName] = useState("");
  const [claims, setClaims] = useState(sampleClaims);
  const [stage, setStage] = useState<"intake" | "assessment" | "result" | "interview" | "decision">("intake");
  const [questions, setQuestions] = useState<AssessmentQuestion[]>([]);
  const [answers, setAnswers] = useState<number[]>([]);
  const [loading, setLoading] = useState(false);
  const [apiNote, setApiNote] = useState("");
  const [recruiterDecision, setRecruiterDecision] = useState<"APPROVE" | "REJECT" | null>(null);
  const [candidateDecision, setCandidateDecision] = useState<"APPROVE" | "REJECT" | null>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const selectedJob = jobs.find((job) => job.id === selectedJobId) ?? jobs[0]!;
  const analysis = useMemo(() => scoreFor(selectedJob, claims), [selectedJob, claims]);
  const filteredJobs = jobs.filter((job) => `${job.title} ${job.department}`.toLowerCase().includes(query.toLowerCase()));
  const completedAnswers = answers.filter((answer) => answer !== undefined).length;
  const correctAnswers = questions.filter((question, index) => answers[index] === question.correctIndex).length;
  const knowledgeScore = questions.length ? Math.round((correctAnswers / questions.length) * 100) : 0;
  const finalScore = Math.round(analysis.score * 0.55 + knowledgeScore * 0.45);

  const handleFile = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setFileName(file.name); if (file.type === "application/pdf") { setLoading(true); try { const result = await analyzeResume(file); setClaims(result.recruiterSummary || result.candidateSummary); setApiNote("วิเคราะห์ Resume ด้วย Gemini API สำเร็จ"); } catch { setApiNote("API วิเคราะห์ Resume ไม่พร้อม — ใช้ข้อความสังเคราะห์เพื่อให้เดโม่ทำต่อได้"); } finally { setLoading(false); } } };
  const createAssessment = async () => { setLoading(true); setApiNote(""); try { const items = await generateAssessment({ jobTitle: selectedJob.title, jobSummary: selectedJob.summary, requiredSkills: selectedJob.skills, resumeEvidence: claims }); setQuestions(items); setAnswers(Array(10).fill(undefined)); setApiNote("สร้างข้อสอบ 10 ข้อด้วย Gemini API แล้ว"); setStage("assessment"); } catch { const fallback = Array.from({length:10},(_,i):AssessmentQuestion => { const skill=selectedJob.skills[i%selectedJob.skills.length]!; return ({ id:`fallback-${i}`, skill, question:`ข้อใดแสดงความเข้าใจ ${skill} ที่เหมาะกับงาน ${selectedJob.title} มากที่สุด?`, options:["เลือกวิธีตามบริบทและอธิบาย trade-off ได้","ใช้วิธีเดิมทุกสถานการณ์","ข้ามการตรวจสอบผลลัพธ์","ตัดสินจากความรู้สึกเท่านั้น"], correctIndex:0, explanation:"คำตอบที่ดีต้องเลือกตามบริบทและอธิบายเหตุผลที่ตรวจสอบได้" }); }); setQuestions(fallback); setAnswers(Array(10).fill(undefined)); setApiNote("Gemini API ไม่พร้อม — ใช้ชุดสำรอง deterministic สำหรับเดโม่"); setStage("assessment"); } finally { setLoading(false); } };
  const reset = () => { setFileName(""); setClaims(sampleClaims); setAnswers([]); setQuestions([]); setRecruiterDecision(null); setCandidateDecision(null); setStage("intake"); if (inputRef.current) inputRef.current.value = ""; };

  return <div className="rec-demo-root">
    <a className="skip-link" href="#main-content">ข้ามไปเนื้อหาหลัก</a>
    <header className="rec-demo-header"><div className="rec-demo-brand"><span>MM</span><div><strong>MaskedMatch</strong><small>Recruiter Intelligence</small></div></div><div className="rec-demo-header-actions"><span className="demo-badge">LOCAL SYNTHETIC DEMO</span><button type="button" onClick={reset}><RotateCcw/> เริ่มเดโม่ใหม่</button></div></header>
    <main id="main-content" className="rec-demo-main">
      <section className="rec-demo-hero"><div><span className="eyebrow">Recruiter-only workspace</span><h1>ตรวจคนให้ตรงงาน<br/><em>ด้วยหลักฐาน ไม่ใช่แค่คีย์เวิร์ด</em></h1><p>แนบเรซูเม่ วิเคราะห์สิ่งที่ผู้สมัครเขียน เทียบ JD และสร้าง assessment เฉพาะบุคคล เพื่อยืนยันว่าความรู้จริงสอดคล้องกับคำกล่าวอ้าง</p></div><div className="rec-demo-metrics"><div><BriefcaseBusiness/><strong>7</strong><span>ตำแหน่งพร้อมเดโม่</span></div><div><Users/><strong>1</strong><span>ผู้สมัครในกระบวนการ</span></div><div><ShieldCheck/><strong>100%</strong><span>ข้อมูลสังเคราะห์</span></div></div></section>
      <nav className="rec-demo-steps" aria-label="ขั้นตอนการประเมิน">{([['intake','1','Resume ↔ JD'],['assessment','2','ข้อสอบ 10 ข้อ'],['result','3','สรุปก่อนคุย'],['interview','4','Masked HR'],['decision','5','ตัดสินใจ']] as const).map(([key,num,label]) => <button key={key} type="button" className={stage === key ? "active" : ""} disabled><span>{num}</span>{label}</button>)}</nav>
      <div className="rec-demo-layout">
        <aside className="rec-job-panel"><div className="rec-section-title"><div><span className="eyebrow">Job catalog</span><h2>เลือกตำแหน่งงาน</h2></div><span>{jobs.length} roles</span></div><label className="rec-search"><Search/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="ค้นหาตำแหน่ง..." aria-label="ค้นหาตำแหน่งงาน"/></label><div className="rec-job-list">{filteredJobs.map((job) => <button type="button" key={job.id} className={selectedJobId === job.id ? "selected" : ""} onClick={() => { setSelectedJobId(job.id); setStage("intake"); }}><span className={job.category === "Tech" ? "tech" : "other"}>{job.category}</span><strong>{job.title}</strong><small>{job.department} · {job.salary}</small><ArrowRight/></button>)}</div></aside>
        <section className="rec-work-panel"><div className="rec-job-detail"><div><span className="eyebrow">Selected JD</span><h2>{selectedJob.title}</h2><p>{selectedJob.summary}</p></div><div className="rec-job-meta"><span>{selectedJob.location}</span><span>{selectedJob.type}</span><strong>{selectedJob.salary}</strong></div></div><div className="rec-skill-row">{selectedJob.skills.map((skill) => <span key={skill}>{skill}</span>)}</div>
          {stage === "intake" && <div className="rec-stage-content"><div className="rec-stage-heading"><span><Upload/></span><div><h3>แนบเรซูเม่ผู้สมัคร</h3><p>PDF จะถูกวิเคราะห์ด้วย API และไม่บันทึกไฟล์ต้นฉบับ</p></div></div><button className={`rec-upload ${fileName ? "has-file" : ""}`} type="button" onClick={() => inputRef.current?.click()}><input ref={inputRef} type="file" accept=".pdf" onChange={handleFile}/>{fileName ? <CheckCircle2/> : <FileText/>}<strong>{loading ? "กำลังวิเคราะห์..." : fileName || "เลือกไฟล์เรซูเม่ PDF"}</strong><span>{fileName ? "แนบไฟล์แล้ว · พร้อมประมวลผล" : "คลิกเพื่อเลือกไฟล์"}</span></button>{apiNote && <div className="rec-ai-note"><Sparkles/><div>{apiNote}</div></div>}<label className="rec-claims"><span>หลักฐานที่สกัดจากเรซูเม่</span><textarea value={claims} onChange={(e) => setClaims(e.target.value)} rows={6}/></label><div className="rec-analysis-preview"><div><span>JD coverage</span><strong>{analysis.score}%</strong></div><div><span>ตรงกับ JD</span><p>{analysis.matched.join(" · ") || "ยังไม่พบทักษะที่ตรง"}</p></div><div><span>ควรตรวจเพิ่ม</span><p>{analysis.missing.join(" · ") || "ครบทุกรายการหลัก"}</p></div></div><button className="rec-primary" type="button" disabled={loading || !fileName || claims.trim().length < 30} onClick={createAssessment}><Sparkles/> {loading ? "กำลังสร้างด้วย API..." : "สร้างข้อสอบ 4 ตัวเลือก 10 ข้อ"} <ArrowRight/></button></div>}
          {stage === "assessment" && <div className="rec-stage-content"><div className="rec-stage-heading"><span><ClipboardCheck/></span><div><h3>Assessment 10 ข้อ · 4 ตัวเลือก</h3><p>{apiNote}</p></div></div><div className="rec-question-list">{questions.map((question, index) => <fieldset key={question.id}><legend>ข้อ {index + 1}/10 · {question.skill}</legend><strong>{question.question}</strong>{question.options.map((option, optionIndex) => <label className="rec-choice" key={option}><input type="radio" name={question.id} checked={answers[index] === optionIndex} onChange={() => setAnswers((current) => { const next=[...current]; next[index]=optionIndex; return next; })}/><span>{String.fromCharCode(65+optionIndex)}</span>{option}</label>)}</fieldset>)}</div><button className="rec-primary" type="button" disabled={completedAnswers < 10} onClick={() => setStage("result")}><ClipboardCheck/> ส่งคำตอบและสรุปผล <ArrowRight/></button></div>}
          {stage === "result" && <div className="rec-stage-content"><div className="rec-result-hero"><span className={finalScore >= 70 ? "pass" : "review"}>{finalScore >= 70 ? <CheckCircle2/> : <Search/>}</span><div><span className="eyebrow">Pre-interview summary</span><h3>{finalScore >= 70 ? "ความรู้สอดคล้องกับ Resume และ JD" : "ควรให้ HR ตรวจเพิ่มระหว่างคุย"}</h3><p>สรุปก่อนเข้าสนทนาแบบปิดบังตัวตน: ตอบถูก {correctAnswers}/10 ข้อ และตรง JD {analysis.matched.length}/{selectedJob.skills.length} ทักษะ</p></div><strong className="rec-final-score">{finalScore}<small>/100</small></strong></div><div className="rec-score-grid"><div><span>Resume ↔ JD</span><strong>{analysis.score}%</strong></div><div><span>Claim evidence</span><strong>{analysis.evidence}%</strong></div><div><span>Knowledge check</span><strong>{knowledgeScore}%</strong><p>{correctAnswers}/10 ข้อ</p></div></div><div className="rec-verdict"><h4>ประเด็นให้ HR ถามต่อ</h4><ul>{analysis.missing.map((skill) => <li className="warn" key={skill}><Search/> ตรวจความรู้เรื่อง {skill}</li>)}<li><Check/> ขอให้เล่าหลักฐานเชิงผลลัพธ์โดยไม่เปิดเผยตัวตน</li></ul></div><div className="rec-actions"><button className="rec-primary" type="button" onClick={() => setStage("interview")}><ShieldCheck/> เข้าห้องคุยแบบใส่หน้ากาก <ArrowRight/></button></div></div>}
          {stage === "interview" && <div className="rec-stage-content"><div className="masked-interview"><div className="masked-person"><ShieldCheck/><strong>Candidate #7F2A</strong><span>Identity protected · Camera masked · ไม่บันทึกการสนทนา</span></div><div className="masked-person hr"><Users/><strong>HR Recruiter</strong><span>พร้อมสนทนา · 15 นาที</span></div></div><div className="rec-ai-note"><ShieldCheck/><div><strong>Masked interview demo</strong><p>ทั้งสองฝั่งเห็นเฉพาะ avatar และข้อมูลทักษะ หลังจบจึงตัดสินใจแบบ private โดยยังไม่เห็นคำตอบของอีกฝ่าย</p></div></div><button className="rec-primary" type="button" onClick={() => setStage("decision")}><Check/> จบการสนทนาและตัดสินใจ</button></div>}
          {stage === "decision" && <div className="rec-stage-content"><div className="rec-stage-heading"><span><ShieldCheck/></span><div><h3>Private two-sided decision</h3><p>เลือกผลทั้งสองฝั่งเพื่อจำลอง resolver แบบเดิม ผลจะเปิดเมื่อส่งครบเท่านั้น</p></div></div><div className="rec-score-grid"><div><span>Recruiter decision</span><button className="rec-primary" onClick={() => setRecruiterDecision("APPROVE")}>สนใจไปต่อ</button> <button className="rec-secondary" onClick={() => setRecruiterDecision("REJECT")}>ไม่ไปต่อ</button></div><div><span>Candidate decision (demo)</span><button className="rec-primary" onClick={() => setCandidateDecision("APPROVE")}>สนใจไปต่อ</button> <button className="rec-secondary" onClick={() => setCandidateDecision("REJECT")}>ไม่ไปต่อ</button></div><div><span>Result</span><strong>{!recruiterDecision || !candidateDecision ? "รอทั้งสองฝั่ง" : recruiterDecision === "APPROVE" && candidateDecision === "APPROVE" ? "Mutual Match" : "No Match"}</strong></div></div>{recruiterDecision && candidateDecision && <div className="rec-result-hero"><span><CheckCircle2/></span><div><h3>{recruiterDecision === "APPROVE" && candidateDecision === "APPROVE" ? "ทั้งสองฝ่ายสนใจตรงกัน" : "จบกระบวนการอย่างเป็นส่วนตัว"}</h3><p>{recruiterDecision === "APPROVE" && candidateDecision === "APPROVE" ? "พร้อมขอ consent เปิดเผยข้อมูลติดต่อในขั้นถัดไป" : "ไม่เปิดเผยว่าใครเลือกไม่ไปต่อ และยังคงปิดบังตัวตน"}</p></div></div>}<div className="rec-actions"><button className="rec-primary" type="button" onClick={reset}>จบและเริ่มรายใหม่</button></div></div>}
        </section>
      </div>
    </main>
    <footer className="rec-demo-footer"><span><ShieldCheck/> Local demo · ไม่มีการอัปโหลดไฟล์ไปยังเซิร์ฟเวอร์</span><span>Recruiter surface only · โค้ดส่วนอื่นยังคงอยู่แต่ไม่เปิด route</span></footer>
  </div>;
}
